services:
  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      SPORTS_SERVICE_URL: http://sports-service:5001
      USER_SERVICE_URL: http://user-service:5002
    depends_on:
      - sports-service
      - user-service
    networks:
      - app-network


  sports-service:
    build:
      context: ./sports-service
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      MONGO_URL: mongodb://mongo:27017/sports_database
    depends_on:
      - mongo
    networks:
      - app-network

  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    ports:
      - "5002:5002"
    environment:
      MONGO_URL: mongodb://mongo:27017/user_database
    depends_on:
      - mongo
    networks:
      - app-network

  websocket-service:
    build:
      context: ./websocket
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    networks:
      - app-network

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      - app-network

  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge