global:
  scrape_interval: 15s
  scrape_timeout: 10s

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:5002']
    metrics_path: '/metrics'

  - job_name: 'sports-service'
    static_configs:
      - targets: ['sports-service:5001']
    metrics_path: '/metrics'