# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: sports_service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'sports_service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14sports_service.proto\x12\rsportsservice\"\x1e\n\x0bPingRequest\x12\x0f\n\x07message\x18\x01 \x01(\t\".\n\x0cPingResponse\x12\x10\n\x08response\x18\x01 \x01(\t\x12\x0c\n\x04load\x18\x02 \x01(\x05\x32P\n\rSportsService\x12?\n\x04Ping\x12\x1a.sportsservice.PingRequest\x1a\x1b.sportsservice.PingResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'sports_service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PINGREQUEST']._serialized_start=39
  _globals['_PINGREQUEST']._serialized_end=69
  _globals['_PINGRESPONSE']._serialized_start=71
  _globals['_PINGRESPONSE']._serialized_end=117
  _globals['_SPORTSSERVICE']._serialized_start=119
  _globals['_SPORTSSERVICE']._serialized_end=199
# @@protoc_insertion_point(module_scope)
